import React, { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { useToast } from '../components/Toast'
import LinkModal from '../components/LinkModal'
import LinkList from '../components/LinkList'
import {
  collection, addDoc, getDocs, query, where, orderBy, serverTimestamp,
} from 'firebase/firestore'
import { db } from '../firebase'
import { apiUrl } from '../lib/runtimeConfig'

export default function HRDashboard() {
  const { currentUser } = useAuth()
  const navigate = useNavigate()
  const toast = useToast()
  const [tab, setTab] = useState('overview')
  const [campaigns, setCampaigns] = useState([])
  const [recentSessions, setRecentSessions] = useState([])
  const [loadingCampaigns, setLoadingCampaigns] = useState(true)

  const [autoRole, setAutoRole] = useState('fullstack')
  const [autoTitle, setAutoTitle] = useState('')
  const [autoExp, setAutoExp] = useState('3-5')
  const [autoGenerating, setAutoGenerating] = useState(false)
  const [generatedCampaign, setGeneratedCampaign] = useState(null)

  const [quickLinks, setQuickLinks] = useState(() => {
    try { return JSON.parse(localStorage.getItem('hr_quick_links') || '[]') } catch { return [] }
  })

  const [form, setForm] = useState({ title: '', jobDescription: '', skills: '', experienceYears: '0-2' })
  const [resumeFile, setResumeFile] = useState(null)
  const [creating, setCreating] = useState(false)

  // Link generation modal
  const [showLinkModal, setShowLinkModal] = useState(false)
  const [linkRefresh, setLinkRefresh] = useState(0)

  useEffect(() => {
    loadCampaigns()
    loadRecentSessions()
  }, [currentUser])

  async function loadCampaigns() {
    setLoadingCampaigns(true)
    try {
      const q = query(collection(db, 'campaigns'), where('hrId', '==', currentUser.uid), orderBy('createdAt', 'desc'))
      const timeout = new Promise((_, rej) => setTimeout(() => rej(), 4000))
      const snap = await Promise.race([getDocs(q), timeout])
      setCampaigns(snap.docs.map(d => ({ id: d.id, ...d.data() })))
    } catch { /* Firestore offline */ }
    setLoadingCampaigns(false)
  }

  async function loadRecentSessions() {
    if (!currentUser?.uid) return
    try {
      const q = query(collection(db, 'sessions'), where('hrId', '==', currentUser.uid))
      const timeout = new Promise((_, rej) => setTimeout(() => rej(), 4000))
      const snap = await Promise.race([getDocs(q), timeout])
      const data = snap?.docs?.map(d => ({ id: d.id, ...d.data() })) || []
      data.sort((a, b) => {
        const da = a.startedAt?.toDate ? a.startedAt.toDate() : new Date(a.startedAt || 0)
        const db2 = b.startedAt?.toDate ? b.startedAt.toDate() : new Date(b.startedAt || 0)
        return db2 - da
      })
      setRecentSessions(data.slice(0, 6))
    } catch {
      setRecentSessions([])
    }
  }

  function generateQuickLink() {
    const id = 'hr-' + Math.random().toString(36).slice(2, 8) + '-' + Date.now().toString(36)
    const link = { id, title: form.title || 'Interview Session', createdAt: new Date().toISOString(), url: `${window.location.origin}/interview/${id}`, observeUrl: `${window.location.origin}/observe/${id}` }
    const updated = [link, ...quickLinks]
    setQuickLinks(updated)
    localStorage.setItem('hr_quick_links', JSON.stringify(updated))
    toast.success('Interview link generated!')
    return link
  }

  function removeQuickLink(id) {
    const updated = quickLinks.filter(l => l.id !== id)
    setQuickLinks(updated)
    localStorage.setItem('hr_quick_links', JSON.stringify(updated))
  }

  function copyText(text) {
    navigator.clipboard.writeText(text).then(() => toast.info('Copied!')).catch(() => {})
  }

  async function handleAutoGenerate() {
    setAutoGenerating(true)
    setGeneratedCampaign(null)
    try {
      const res = await fetch(apiUrl('/api/auto-generate-campaign'), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ role_type: autoRole, title: autoTitle || undefined, experience_level: autoExp }),
      })
      if (res.ok) {
        const data = await res.json()
        setGeneratedCampaign(data)
        toast.success(`Campaign generated! ${data.questionCount} questions for ${data.title}.`)
        const id = 'auto-' + Math.random().toString(36).slice(2, 8) + '-' + Date.now().toString(36)
        const link = { id, title: data.title, createdAt: new Date().toISOString(), url: `${window.location.origin}/interview/${id}`, observeUrl: `${window.location.origin}/observe/${id}`, autoGenerated: true, roleType: autoRole, questionCount: data.questionCount }
        const updated = [link, ...quickLinks]
        setQuickLinks(updated)
        localStorage.setItem('hr_quick_links', JSON.stringify(updated))
      } else {
        toast.error('Failed to generate campaign.')
      }
    } catch (err) {
      toast.error(`Error: ${err.message}`)
    }
    setAutoGenerating(false)
  }

  async function handleCreate(e) {
    e.preventDefault()
    setCreating(true)
    try {
      let parsedSkills = form.skills
      if (resumeFile) {
        const fd = new FormData()
        fd.append('resume', resumeFile)
        fd.append('job_description', form.jobDescription)
        const res = await fetch(apiUrl('/api/parse-resume'), { method: 'POST', body: fd })
        if (res.ok) { const data = await res.json(); parsedSkills = data.skills?.join(', ') || form.skills }
      }
      const poolRes = await fetch(apiUrl('/api/generate-question-pool'), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ job_title: form.title, job_description: form.jobDescription, required_skills: parsedSkills, experience_years: form.experienceYears }),
      })
      const poolData = poolRes.ok ? await poolRes.json() : { questions: [] }
      await addDoc(collection(db, 'campaigns'), {
        hrId: currentUser.uid, title: form.title, jobDescription: form.jobDescription,
        requiredSkills: parsedSkills, experienceYears: form.experienceYears,
        questionPool: poolData.questions || [], createdAt: serverTimestamp(), status: 'active',
      })
      toast.success(`Campaign created! ${poolData.questions?.length || 0} questions generated.`)
      setForm({ title: '', jobDescription: '', skills: '', experienceYears: '0-2' })
      setResumeFile(null)
      loadCampaigns()
      setTab('campaigns')
    } catch (err) {
      toast.error(`Failed: ${err.message}`)
    }
    setCreating(false)
  }

  const tabs = [
    { key: 'overview', label: 'Overview' },
    { key: 'auto', label: 'Auto Generate' },
    { key: 'campaigns', label: 'Campaigns' },
    { key: 'create', label: 'New Campaign' },
  ]
  const completedSessions = recentSessions.filter(s => s.status === 'completed')

  return (
    <div className="page-enter" style={{ minHeight: 'calc(100vh - 60px)', background: '#f7f6fb' }}>
      <div className="container" style={{ padding: '32px 24px', maxWidth: '1120px' }}>

        {/* Greeting + tabs row */}
        <div style={S.topRow}>
          <div>
            <h1 style={S.greeting}>
              Welcome, <span style={{ color: 'var(--primary)' }}>{currentUser.email?.split('@')[0]}</span>
            </h1>
            <p style={S.greetingSub}>Manage interviews, generate links, and observe candidates live.</p>
          </div>
          <div style={S.topStats}>
            <div style={S.topStat}>
              <span style={S.topStatNum}>{quickLinks.length}</span>
              <span style={S.topStatLabel}>Active Links</span>
            </div>
            <div style={S.topStatDivider} />
            <div style={S.topStat}>
              <span style={S.topStatNum}>{campaigns.length}</span>
              <span style={S.topStatLabel}>Campaigns</span>
            </div>
            <div style={S.topStatDivider} />
            <div style={S.topStat}>
              <span style={S.topStatNum}>{completedSessions.length}</span>
              <span style={S.topStatLabel}>Reports</span>
            </div>
          </div>
        </div>

        {/* Tabs */}
        <div style={S.tabRow}>
          {tabs.map(t => (
            <button
              key={t.key}
              onClick={() => setTab(t.key)}
              style={tab === t.key ? { ...S.tab, ...S.tabActive } : S.tab}
            >
              {t.label}
              {tab === t.key && <div style={S.tabIndicator} />}
            </button>
          ))}
        </div>

        {/* ═══ LINK MODAL ═══ */}
        <LinkModal
          isOpen={showLinkModal}
          onClose={() => setShowLinkModal(false)}
          mode="hr"
          userId={currentUser.uid}
          userEmail={currentUser.email}
          campaigns={campaigns}
          onLinkCreated={() => setLinkRefresh(r => r + 1)}
        />

        {/* ═══ OVERVIEW ═══ */}
        {tab === 'overview' && (
          <>
            {/* Quick link generator card */}
            <div style={S.genCard}>
              <div style={S.genCardLeft}>
                <div style={S.genIconBox}>
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2"><path d="M10 13a5 5 0 007.54.54l3-3a5 5 0 00-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 00-7.54-.54l-3 3a5 5 0 007.07 7.07l1.71-1.71"/></svg>
                </div>
                <div>
                  <h2 style={S.genTitle}>Generate Interview Link</h2>
                  <p style={S.genSub}>Create a one-time link instantly. No campaign setup needed.</p>
                </div>
              </div>
              <div style={S.genCardRight}>
                <input
                  value={form.title}
                  onChange={e => setForm(f => ({ ...f, title: e.target.value }))}
                  placeholder="Session name (optional)"
                  style={S.genInput}
                />
                <button className="btn btn-primary" style={S.genBtn} onClick={generateQuickLink}>
                  Quick Link
                </button>
                <button className="btn btn-outline" style={{ ...S.genBtn, background: 'transparent', color: 'var(--primary)', border: '1.5px solid var(--primary)' }} onClick={() => setShowLinkModal(true)}>
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{ marginRight: '4px' }}><rect x="2" y="4" width="20" height="16" rx="0"/><path d="M22 4L12 13 2 4"/></svg>
                  Send via Email
                </button>
              </div>
            </div>

            {/* Links list */}
            {quickLinks.length > 0 && (
              <div style={{ marginTop: '24px' }}>
                <div style={S.sectionHeader}>
                  <h3 style={S.sectionTitle}>Interview Links</h3>
                  <span style={S.sectionCount}>{quickLinks.length}</span>
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                  {quickLinks.map(link => (
                    <div key={link.id} style={S.linkCard}>
                      <div style={S.linkCardTop}>
                        <div style={{ flex: 1 }}>
                          <div style={S.linkTitle}>{link.title}</div>
                          <div style={S.linkMeta}>
                            {new Date(link.createdAt).toLocaleDateString()} &middot; {link.id.slice(0, 16)}...
                          </div>
                        </div>
                        <button style={S.removeBtn} onClick={() => removeQuickLink(link.id)}>
                          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
                        </button>
                      </div>
                      <div style={S.linkUrlRow}>
                        <code style={S.linkUrl}>{link.url}</code>
                        <button style={S.copyBtn} onClick={() => copyText(link.url)}>Copy</button>
                      </div>
                      <div style={S.linkActions}>
                        <button style={S.watchBtn} onClick={() => navigate(`/observe/${link.id}`)}>
                          <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="10"/><polygon points="10 8 16 12 10 16 10 8"/></svg>
                          Watch Live
                        </button>
                        <button style={S.secondaryBtn} onClick={() => copyText(link.url)}>
                          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/></svg>
                          Share Link
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {quickLinks.length === 0 && (
              <div style={S.emptyState}>
                <div style={S.emptyIcon}>
                  <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="var(--primary)" strokeWidth="1.5" opacity="0.5"><path d="M10 13a5 5 0 007.54.54l3-3a5 5 0 00-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 00-7.54-.54l-3 3a5 5 0 007.07 7.07l1.71-1.71"/></svg>
                </div>
                <p style={S.emptyTitle}>No interview links yet</p>
                <p style={S.emptySub}>Generate your first link above to get started.</p>
              </div>
            )}

            <div style={{ marginTop: '28px' }}>
              <div style={S.sectionHeader}>
                <h3 style={S.sectionTitle}>Recent Interview Activity</h3>
                <span style={S.sectionCount}>{recentSessions.length}</span>
              </div>
              {recentSessions.length === 0 ? (
                <div style={S.emptyState}>
                  <div style={S.emptyIcon}>📋</div>
                  <p style={S.emptyTitle}>No interview activity yet</p>
                  <p style={S.emptySub}>Completed interviews and live sessions will appear here automatically.</p>
                </div>
              ) : (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                  {recentSessions.map(session => {
                    const date = session.startedAt?.toDate
                      ? session.startedAt.toDate().toLocaleString()
                      : new Date(session.startedAt || 0).toLocaleString()
                    const score = session.overallScore
                    return (
                      <div key={session.id} style={S.linkCard}>
                        <div style={S.linkCardTop}>
                          <div style={{ flex: 1 }}>
                            <div style={S.linkTitle}>{session.candidateName || session.candidateEmail || session.candidateId || 'Candidate Session'}</div>
                            <div style={S.linkMeta}>
                              {(session.campaignTitle || session.jobTitle || 'Interview Session')} · {date}
                            </div>
                          </div>
                          <span className={`badge badge-${session.status === 'completed' ? 'success' : 'warning'}`}>
                            {session.status || 'in-progress'}
                          </span>
                        </div>
                        <div style={S.linkActions}>
                          <div style={{ fontSize: '13px', color: 'var(--text-muted)' }}>
                            Score:{' '}
                            <strong style={{ color: score >= 70 ? 'var(--success)' : score >= 40 ? 'var(--warning)' : score != null ? 'var(--danger)' : 'var(--text-muted)' }}>
                              {score ?? 'Pending'}
                            </strong>
                          </div>
                          <div style={{ display: 'flex', gap: '8px' }}>
                            {session.campaignId && (
                              <button style={S.watchBtn} onClick={() => navigate(`/observe/${session.campaignId}`)}>
                                Watch Live
                              </button>
                            )}
                            {session.status === 'completed' && (
                              <button style={S.secondaryBtn} onClick={() => navigate(`/report/${session.id}`)}>
                                View Report
                              </button>
                            )}
                          </div>
                        </div>
                      </div>
                    )
                  })}
                </div>
              )}
            </div>

            {/* Emailed Links (from backend) */}
            <div style={{ marginTop: '28px' }}>
              <div style={S.sectionHeader}>
                <h3 style={S.sectionTitle}>Emailed Interview Links</h3>
              </div>
              <LinkList userId={currentUser.uid} mode="hr" refresh={linkRefresh} />
            </div>

            {/* How it works */}
            <div style={S.howSection}>
              <h3 style={{ ...S.sectionTitle, marginBottom: '16px' }}>How it works</h3>
              <div style={S.howGrid}>
                {[
                  { num: '1', title: 'Generate', desc: 'Create a unique interview link' },
                  { num: '2', title: 'Share', desc: 'Send the link to your candidate' },
                  { num: '3', title: 'Interview', desc: 'AI asks questions via voice' },
                  { num: '4', title: 'Observe', desc: 'Watch the interview live' },
                  { num: '5', title: 'Intervene', desc: 'Take over from AI anytime' },
                  { num: '6', title: 'Report', desc: 'Get AI evaluation automatically' },
                ].map(s => (
                  <div key={s.num} style={S.howCard}>
                    <div style={S.howNum}>{s.num}</div>
                    <div>
                      <div style={S.howTitle}>{s.title}</div>
                      <div style={S.howDesc}>{s.desc}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </>
        )}

        {/* ═══ CREATE CAMPAIGN ═══ */}
        {tab === 'create' && (
          <div style={{ maxWidth: '620px' }}>
            <div style={S.sectionHeader}>
              <h3 style={S.sectionTitle}>Create Campaign</h3>
            </div>
            <p style={{ fontSize: '13px', color: 'var(--text-muted)', marginBottom: '20px' }}>
              Create a full campaign with AI-generated questions from 1,400+ curated questions.
            </p>
            <div style={S.formCard}>
              <form onSubmit={handleCreate}>
                <div className="form-group">
                  <label>Job Title *</label>
                  <input value={form.title} onChange={e => setForm(f => ({ ...f, title: e.target.value }))} placeholder="e.g. Senior Backend Engineer" required />
                </div>
                <div className="form-group">
                  <label>Job Description *</label>
                  <textarea value={form.jobDescription} onChange={e => setForm(f => ({ ...f, jobDescription: e.target.value }))} placeholder="Paste the full job description..." style={{ minHeight: '120px' }} required />
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                  <div className="form-group">
                    <label>Required Skills</label>
                    <input value={form.skills} onChange={e => setForm(f => ({ ...f, skills: e.target.value }))} placeholder="Python, Docker, SQL" />
                  </div>
                  <div className="form-group">
                    <label>Experience Level</label>
                    <select value={form.experienceYears} onChange={e => setForm(f => ({ ...f, experienceYears: e.target.value }))}>
                      <option value="0-2">Junior (0-2 yrs)</option>
                      <option value="3-5">Mid (3-5 yrs)</option>
                      <option value="6+">Senior (6+ yrs)</option>
                    </select>
                  </div>
                </div>
                <div className="form-group">
                  <label>Sample Resume (optional)</label>
                  <input type="file" accept=".pdf,.docx" onChange={e => setResumeFile(e.target.files[0])} />
                </div>
                <button type="submit" className="btn btn-primary" disabled={creating} style={{ width: '100%', justifyContent: 'center', padding: '13px' }}>
                  {creating ? <><span className="spinner" style={{ width: '16px', height: '16px' }} /> Generating...</> : 'Create Campaign + Generate Questions'}
                </button>
              </form>
            </div>
          </div>
        )}

        {/* ═══ AUTO GENERATE ═══ */}
        {tab === 'auto' && (
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '28px' }}>
            <div>
              <div style={S.sectionHeader}>
                <h3 style={S.sectionTitle}>Auto Generate Campaign</h3>
              </div>
              <p style={{ fontSize: '13px', color: 'var(--text-muted)', marginBottom: '20px' }}>
                Pick a role and we'll generate 20 questions instantly from our curated dataset.
              </p>

              <div style={S.formCard}>
                <label style={{ fontSize: '12px', fontWeight: 700, color: 'var(--text-muted)', letterSpacing: '0.08em', marginBottom: '10px', display: 'block' }}>ROLE TYPE</label>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '8px', marginBottom: '20px' }}>
                  {[
                    { key: 'frontend', label: 'Frontend' },
                    { key: 'backend', label: 'Backend' },
                    { key: 'fullstack', label: 'Full Stack' },
                    { key: 'data', label: 'Data' },
                    { key: 'devops', label: 'DevOps' },
                    { key: 'mobile', label: 'Mobile' },
                    { key: 'qa', label: 'QA' },
                    { key: 'ml', label: 'ML / AI' },
                  ].map(r => (
                    <button
                      key={r.key}
                      type="button"
                      onClick={() => setAutoRole(r.key)}
                      style={autoRole === r.key ? { ...S.roleChip, ...S.roleChipActive } : S.roleChip}
                    >
                      {r.label}
                    </button>
                  ))}
                </div>

                <div className="form-group">
                  <label>Custom Title (optional)</label>
                  <input value={autoTitle} onChange={e => setAutoTitle(e.target.value)} placeholder="Leave blank for auto-title" />
                </div>
                <div className="form-group">
                  <label>Experience Level</label>
                  <select value={autoExp} onChange={e => setAutoExp(e.target.value)}>
                    <option value="0-2">Junior (0-2 yrs)</option>
                    <option value="3-5">Mid (3-5 yrs)</option>
                    <option value="6+">Senior (6+ yrs)</option>
                  </select>
                </div>
                <button className="btn btn-primary" style={{ width: '100%', justifyContent: 'center', padding: '13px' }} onClick={handleAutoGenerate} disabled={autoGenerating}>
                  {autoGenerating ? <><span className="spinner" style={{ width: '16px', height: '16px' }} /> Generating...</> : 'Generate Campaign'}
                </button>
              </div>
            </div>

            <div>
              {generatedCampaign ? (
                <>
                  <div style={S.sectionHeader}>
                    <h3 style={S.sectionTitle}>Generated Campaign</h3>
                    <span className="badge badge-success">Ready</span>
                  </div>
                  <div style={S.formCard}>
                    <h4 style={{ fontFamily: 'var(--font-head)', fontSize: '20px', marginBottom: '8px' }}>{generatedCampaign.title}</h4>
                    <p style={{ fontSize: '13px', color: 'var(--text-muted)', marginBottom: '12px' }}>{generatedCampaign.jobDescription}</p>
                    <div style={{ display: 'flex', gap: '12px', fontSize: '12px', color: 'var(--text-muted)', marginBottom: '12px' }}>
                      <span>{generatedCampaign.questionCount} questions</span>
                      <span>{generatedCampaign.experienceYears} yrs exp</span>
                    </div>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
                      {generatedCampaign.requiredSkills.split(',').slice(0, 8).map((s, i) => (
                        <span key={i} style={S.skillTag}>{s.trim()}</span>
                      ))}
                    </div>
                  </div>
                  <div style={{ marginTop: '12px' }}>
                    <div style={S.questionList}>
                      {generatedCampaign.questions.map((q, i) => (
                        <div key={i} style={S.questionRow}>
                          <span style={S.qNum}>Q{i + 1}</span>
                          <div style={{ flex: 1 }}>
                            <p style={{ fontSize: '13px', lineHeight: '1.5', margin: 0 }}>{q.text}</p>
                          </div>
                          <span className={`badge badge-${q.difficulty === 'advanced' ? 'danger' : q.difficulty === 'intermediate' ? 'warning' : 'success'}`} style={{ fontSize: '9px', flexShrink: 0 }}>{q.difficulty}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                </>
              ) : (
                <div style={S.emptyState}>
                  <div style={S.emptyIcon}>
                    <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="var(--primary)" strokeWidth="1.5" opacity="0.5"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg>
                  </div>
                  <p style={S.emptyTitle}>No campaign generated yet</p>
                  <p style={S.emptySub}>Select a role type and click generate to create a full question set.</p>
                </div>
              )}
            </div>
          </div>
        )}

        {/* ═══ CAMPAIGNS ═══ */}
        {tab === 'campaigns' && (
          <>
            <div style={S.sectionHeader}>
              <h3 style={S.sectionTitle}>Your Campaigns</h3>
              {campaigns.length > 0 && <span style={S.sectionCount}>{campaigns.length}</span>}
            </div>
            {loadingCampaigns ? (
              <div style={{ padding: '60px', textAlign: 'center' }}><span className="spinner" /></div>
            ) : campaigns.length === 0 ? (
              <div style={S.emptyState}>
                <div style={S.emptyIcon}>
                  <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="var(--primary)" strokeWidth="1.5" opacity="0.5"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>
                </div>
                <p style={S.emptyTitle}>No campaigns yet</p>
                <p style={S.emptySub}>Campaigns require Firestore. Use Quick Links for instant sessions.</p>
                <button className="btn btn-primary" style={{ marginTop: '16px' }} onClick={() => setTab('create')}>Create Campaign</button>
              </div>
            ) : (
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))', gap: '16px' }}>
                {campaigns.map(c => <CampaignCard key={c.id} campaign={c} />)}
              </div>
            )}
          </>
        )}
      </div>
    </div>
  )
}

function CampaignCard({ campaign }) {
  const navigate = useNavigate()
  const toast = useToast()
  const link = `${window.location.origin}/interview/${campaign.id}`
  function copyLink() { navigator.clipboard.writeText(link).then(() => toast.info('Copied!')).catch(() => {}) }
  const poolSize = campaign.questionPool?.length || 0
  const hasDate = campaign.createdAt && typeof campaign.createdAt.toDate === 'function'
  const date = hasDate ? campaign.createdAt.toDate().toLocaleDateString() : 'N/A'

  return (
    <div style={S.campaignCard}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '12px' }}>
        <div>
          <h4 style={{ fontFamily: 'var(--font-head)', fontSize: '18px', margin: 0 }}>{campaign.title}</h4>
          <span style={{ fontSize: '11px', color: 'var(--text-muted)' }}>{date}</span>
        </div>
        <span className={`badge badge-${campaign.status === 'active' ? 'success' : 'warning'}`} style={{ fontSize: '10px' }}>{campaign.status}</span>
      </div>
      <div style={{ display: 'flex', gap: '16px', fontSize: '12px', color: 'var(--text-muted)', marginBottom: '10px' }}>
        <span>{poolSize} questions</span>
        <span>{campaign.experienceYears} yrs</span>
      </div>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px', marginBottom: '14px' }}>
        {(campaign.requiredSkills || '').split(',').slice(0, 4).map((s, i) => (
          <span key={i} style={S.skillTag}>{s.trim()}</span>
        ))}
      </div>
      <div style={{ borderTop: '1px solid #eee', paddingTop: '12px', display: 'flex', gap: '8px' }}>
        <button style={S.watchBtn} onClick={() => navigate(`/observe/${campaign.id}`)}>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="10"/><polygon points="10 8 16 12 10 16 10 8"/></svg>
          Watch Live
        </button>
        <button style={S.secondaryBtn} onClick={copyLink}>Copy Link</button>
        <button style={S.secondaryBtn} onClick={() => navigate(`/hr/campaign/${campaign.id}/sessions`)}>Sessions</button>
      </div>
    </div>
  )
}

const S = {
  // ── Top area ──
  topRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '28px',
    gap: '20px',
    flexWrap: 'wrap',
  },
  greeting: {
    fontFamily: 'var(--font-head)',
    fontSize: '28px',
    margin: 0,
    lineHeight: 1.2,
  },
  greetingSub: {
    fontSize: '14px',
    color: 'var(--text-muted)',
    marginTop: '4px',
  },
  topStats: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
    background: '#fff',
    padding: '14px 24px',
    border: '1px solid #eee',
    borderRadius: '0px',
  },
  topStat: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '2px',
  },
  topStatNum: {
    fontFamily: 'var(--font-head)',
    fontSize: '26px',
    color: 'var(--primary)',
    lineHeight: 1,
  },
  topStatLabel: {
    fontSize: '10px',
    fontWeight: 600,
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  topStatDivider: {
    width: '1px',
    height: '32px',
    background: '#eee',
  },

  // ── Tabs ──
  tabRow: {
    display: 'flex',
    gap: '0',
    borderBottom: '2px solid #eee',
    marginBottom: '28px',
  },
  tab: {
    padding: '10px 20px',
    fontSize: '13px',
    fontWeight: 600,
    fontFamily: 'var(--font-body)',
    background: 'none',
    border: 'none',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    position: 'relative',
    transition: 'color 0.2s',
  },
  tabActive: {
    color: 'var(--primary)',
  },
  tabIndicator: {
    position: 'absolute',
    bottom: '-2px',
    left: '0',
    right: '0',
    height: '2px',
    background: 'var(--primary)',
  },

  // ── Generate card ──
  genCard: {
    background: '#fff',
    border: '1px solid #eee',
    borderRadius: '0px',
    padding: '24px 28px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '24px',
    flexWrap: 'wrap',
  },
  genCardLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  genIconBox: {
    width: '48px',
    height: '48px',
    background: 'var(--primary)',
    borderRadius: '0px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  genTitle: {
    fontFamily: 'var(--font-head)',
    fontSize: '18px',
    margin: 0,
  },
  genSub: {
    fontSize: '13px',
    color: 'var(--text-muted)',
    margin: '2px 0 0',
  },
  genCardRight: {
    display: 'flex',
    gap: '10px',
    alignItems: 'center',
  },
  genInput: {
    padding: '10px 14px',
    fontSize: '13px',
    border: '1.5px solid #eee',
    borderRadius: '0px',
    width: '220px',
    fontFamily: 'var(--font-body)',
    outline: 'none',
    transition: 'border-color 0.2s',
    background: '#faf9ff',
  },
  genBtn: {
    padding: '10px 24px',
    fontSize: '13px',
    borderRadius: '0px',
    whiteSpace: 'nowrap',
  },

  // ── Section headers ──
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '16px',
  },
  sectionTitle: {
    fontFamily: 'var(--font-head)',
    fontSize: '20px',
    margin: 0,
  },
  sectionCount: {
    background: 'var(--primary-light)',
    color: 'var(--primary)',
    fontSize: '11px',
    fontWeight: 700,
    padding: '2px 10px',
    borderRadius: '0px',
  },

  // ── Link cards ──
  linkCard: {
    background: '#fff',
    border: '1px solid #eee',
    borderRadius: '0px',
    padding: '18px 22px',
    transition: 'box-shadow 0.2s',
  },
  linkCardTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '10px',
  },
  linkTitle: {
    fontWeight: 700,
    fontSize: '14px',
    color: 'var(--text)',
  },
  linkMeta: {
    fontSize: '11px',
    color: 'var(--text-muted)',
    marginTop: '2px',
  },
  removeBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#ccc',
    padding: '4px',
    borderRadius: '0px',
    transition: 'color 0.2s',
  },
  linkUrlRow: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    marginBottom: '12px',
  },
  linkUrl: {
    flex: 1,
    fontSize: '11px',
    padding: '8px 12px',
    background: '#f8f7fc',
    border: '1px solid #eee',
    borderRadius: '0px',
    color: 'var(--text-muted)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontFamily: 'monospace',
  },
  copyBtn: {
    background: 'none',
    border: '1px solid #ddd',
    borderRadius: '0px',
    padding: '7px 14px',
    fontSize: '11px',
    fontWeight: 600,
    cursor: 'pointer',
    color: 'var(--text-muted)',
    fontFamily: 'var(--font-body)',
    transition: 'all 0.2s',
  },
  linkActions: {
    display: 'flex',
    gap: '8px',
  },
  watchBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '8px 18px',
    fontSize: '12px',
    fontWeight: 700,
    background: 'var(--primary)',
    color: '#fff',
    border: 'none',
    borderRadius: '0px',
    cursor: 'pointer',
    fontFamily: 'var(--font-body)',
    transition: 'all 0.2s',
      },
  secondaryBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '8px 16px',
    fontSize: '12px',
    fontWeight: 600,
    background: '#f8f7fc',
    color: 'var(--text-muted)',
    border: '1px solid #eee',
    borderRadius: '0px',
    cursor: 'pointer',
    fontFamily: 'var(--font-body)',
    transition: 'all 0.2s',
  },

  // ── How it works ──
  howSection: {
    marginTop: '36px',
  },
  howGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '12px',
  },
  howCard: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '14px',
    background: '#fff',
    border: '1px solid #eee',
    borderRadius: '0px',
    padding: '18px 20px',
  },
  howNum: {
    width: '30px',
    height: '30px',
    background: 'var(--primary-light)',
    color: 'var(--primary)',
    borderRadius: '0px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: 'var(--font-head)',
    fontSize: '16px',
    flexShrink: 0,
  },
  howTitle: {
    fontWeight: 700,
    fontSize: '13px',
    marginBottom: '2px',
  },
  howDesc: {
    fontSize: '12px',
    color: 'var(--text-muted)',
  },

  // ── Form card ──
  formCard: {
    background: '#fff',
    border: '1px solid #eee',
    borderRadius: '0px',
    padding: '28px',
  },

  // ── Role chips ──
  roleChip: {
    padding: '10px 8px',
    fontSize: '12px',
    fontWeight: 600,
    fontFamily: 'var(--font-body)',
    background: '#f8f7fc',
    border: '1.5px solid #eee',
    borderRadius: '0px',
    cursor: 'pointer',
    color: 'var(--text-muted)',
    transition: 'all 0.2s',
    textAlign: 'center',
  },
  roleChipActive: {
    background: 'var(--primary)',
    borderColor: 'var(--primary)',
    color: '#fff',
  },

  // ── Skill tags ──
  skillTag: {
    fontSize: '10px',
    fontWeight: 600,
    padding: '3px 8px',
    background: '#f3f0ff',
    color: 'var(--primary)',
    borderRadius: '0px',
  },

  // ── Question list ──
  questionList: {
    background: '#fff',
    border: '1px solid #eee',
    borderRadius: '0px',
    maxHeight: '420px',
    overflowY: 'auto',
  },
  questionRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
    padding: '12px 18px',
    borderBottom: '1px solid #f5f5f5',
  },
  qNum: {
    fontFamily: 'var(--font-head)',
    fontSize: '14px',
    color: 'var(--primary)',
    flexShrink: 0,
    marginTop: '1px',
  },

  // ── Campaign card ──
  campaignCard: {
    background: '#fff',
    border: '1px solid #eee',
    borderRadius: '0px',
    padding: '22px 24px',
    transition: 'box-shadow 0.2s, border-color 0.2s',
  },

  // ── Empty state ──
  emptyState: {
    textAlign: 'center',
    padding: '56px 20px',
    background: '#fff',
    border: '1px solid #eee',
    borderRadius: '0px',
    marginTop: '4px',
  },
  emptyIcon: {
    width: '56px',
    height: '56px',
    background: '#f3f0ff',
    borderRadius: '0px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 14px',
  },
  emptyTitle: {
    fontSize: '15px',
    fontWeight: 700,
    color: 'var(--text)',
    margin: 0,
  },
  emptySub: {
    fontSize: '13px',
    color: 'var(--text-muted)',
    marginTop: '4px',
  },
}
